2023-09-27 13:49:19,448 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2023-09-27 13:49:19,451 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
2023-09-27 13:49:23,879 - Debug Adapter (main) - WARNING - The operation took too long! - Measured 4.416965 s ( from ~ 13:49:19,462892)
2023-09-27 13:49:32,441 - Debug Adapter (main) - ERROR - unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 706, in on_setBreakpoints_request
    try_set_once(get_good_path(source.path), src_line, condition)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 677, in try_set_once
    raise e
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 675, in try_set_once
    return self.da.source_break_add(source_path, line, condition=condition)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 523, in source_break_add
    bp_num = self._gdb.add_bp("{}:{}".format(src, line), ignore_count=0, cond=condition)
  File "C:\Users\User\.espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_debug_backend\gdb.py", line 494, in add_bp
    raise DebuggerError('Failed to insert BP!')
esp_debug_backend.defs.DebuggerError: Failed to insert BP!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 712, in on_setBreakpoints_request
    bp.update({{'message': e}})
TypeError: unhashable type: 'dict'
2023-09-27 13:49:37,474 - Debug Adapter (main) - ERROR - unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 706, in on_setBreakpoints_request
    try_set_once(get_good_path(source.path), src_line, condition)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 677, in try_set_once
    raise e
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 675, in try_set_once
    return self.da.source_break_add(source_path, line, condition=condition)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 523, in source_break_add
    bp_num = self._gdb.add_bp("{}:{}".format(src, line), ignore_count=0, cond=condition)
  File "C:\Users\User\.espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_debug_backend\gdb.py", line 494, in add_bp
    raise DebuggerError('Failed to insert BP!')
esp_debug_backend.defs.DebuggerError: Failed to insert BP!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 712, in on_setBreakpoints_request
    bp.update({{'message': e}})
TypeError: unhashable type: 'dict'
2023-09-27 13:49:42,475 - Debug Adapter (main) - ERROR - unhashable type: 'dict'
Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 706, in on_setBreakpoints_request
    try_set_once(get_good_path(source.path), src_line, condition)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 677, in try_set_once
    raise e
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 675, in try_set_once
    return self.da.source_break_add(source_path, line, condition=condition)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\debug_adapter.py", line 523, in source_break_add
    bp_num = self._gdb.add_bp("{}:{}".format(src, line), ignore_count=0, cond=condition)
  File "C:\Users\User\.espressif\python_env\idf5.0_py3.8_env\lib\site-packages\esp_debug_backend\gdb.py", line 494, in add_bp
    raise DebuggerError('Failed to insert BP!')
esp_debug_backend.defs.DebuggerError: Failed to insert BP!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "c:\Users\User\.vscode\extensions\espressif.esp-idf-extension-1.6.4\esp_debug_adapter\debug_adapter\command_processor.py", line 712, in on_setBreakpoints_request
    bp.update({{'message': e}})
TypeError: unhashable type: 'dict'
2023-09-27 13:49:53,418 - Debug Adapter (main) - WARNING - The step operation took too long - Measured 1.007031 s ( from ~ 13:49:52,411428)
2023-09-27 13:49:56,919 - Debug Adapter (main) - WARNING - The step operation took too long - Measured 1.013028 s ( from ~ 13:49:55,906429)
2023-09-27 13:49:57,933 - Debug Adapter (main) - WARNING - The step operation took too long - Measured 1.014003 s ( from ~ 13:49:56,919457)
2023-09-27 13:51:01,576 - Debug Adapter (main) - WARNING - The step operation took too long - Measured 1.508966 s ( from ~ 13:51:00,068008)
2023-09-27 13:51:03,421 - Debug Adapter (main) - WARNING - The step operation took too long - Measured 1.011963 s ( from ~ 13:51:02,410010)
2023-09-27 13:51:04,946 - Debug Adapter (main) - WARNING - The step operation took too long - Measured 1.014038 s ( from ~ 13:51:03,932159)
2023-09-27 13:53:01,738 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
